### ISSUE TITLE
Help with Applause?

### ISSUE THREAD

**Issue by sam-p9** [bhadaway/support#12]
Heyy there
I notice the applause doesn't update.
If we vote on our page [here](https://www.effervescence-citoyenne.xyz/guide-hochelaga/) and then refresh, the count is back to one. 
Can we fix that?
Thank you so much

**Comment by bhadaway** [comment]
Be sure to test liking it from a completely different device/browser/IP. For example, try using your phone while NOT connected to WiFi.

**Comment by sam-p9** [comment]
Oh whoops I must've done something wrong! All of them switched to 2 at the same time. Can we clap different things independently on a same page?

**Comment by bhadaway** [comment]
Ah, so the applause count is based on the page's URL, and unless you explicitly set them to something different, they'll automatically just use whatever's shown in your browser bar.

If you want to set different counts for different parts of the same page, you can use anchors/hashtags, like so:

```
[applause url="https://example.com/#cats"]

[applause url="https://example.com/#dogs"]
```

**Comment by CamiloGarciaLaRotta** [comment]
👋🏼 @bhadaway thanks for the awesome plugin!

I noticed that #fragments are not submitted! I wonder if it is an issue at the WP plugin level or at the underlying https://applause-button.com/ level 🤔 

We ended up removing the `#` even though the URL doesn't point to any page:
```diff
- [applause url="https://example.com/#cats"]
+ [applause url="https://example.com/cats"]
```

Here's a summary

https://github.com/bhadaway/support/assets/17187770/4ffd242e-6fb9-4a65-a2f7-3befd03f2d89

**Comment by bhadaway** [comment]
Yes, I'm guessing that the Applause dev overlooks `#` to avoid duplicates/mismatches. And yes, your solution works fine, as long as the URL doesn't actually exist in order to avoid collision. So, best to use really unique identifiers:

```
[applause url="https://example.com/page-section-1"]
[applause url="https://example.com/page-section-2"]
```
