### ISSUE TITLE
Dark Setting on Devices

### ISSUE THREAD

**Issue by rickhellewell** [bhadaway/support#13]
Using the latest version of the theme, there is an issue with devices that have set a 'dark' theme as their default. This is most noticiable on phone devices, which set the 'dark' theme as a default that has to be overridden by the user to a 'light' theme.

If you view a Pages site with a phone browser (Chrome) that has dark setting enabled. (I noticed this on my Samsung Galaxy phone with the Chrome browser version 123.0.6312.99,  If you go into the Settings for Chrome, then Theme, then look at System Default, there is a setting for Light and Dark, and the default is to use "System Default", which says "Turn on dark theme when your device's dark theme or battery saver is on'.

If the browser settings are set to Dark, then the body text (which has CSS 'color:blank') is reversed so there is a black background and black text. So the text in the body area is not visible. Note that you can't see this in the emulator in browsers when you select any phone device.

There isn't, according to the MSDN docs, a way to force a 'light' mode. You can sense whether the light/dark mode is on (see https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme ) as the user's preferred color scheme, but there is no way to force into 'light' mode.

Now, you can specify a light and dark mode for CSS colors, see https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark . This would require changing the CSS for all colors to include a color setting; see the example in the light-dark link. 

So, the issue is that Pages will not have visible body text if the device is set to dark mode - the text color will be black on black background. And that causes site content visibility with the Pages theme when used on devices that have their preference set to 'dark' mode, either by default or by user preference.

Note that you have to view this issue on a phone device that has dark mode set in Chrome. It is not visible in the Developer Mobile emulation mode.

**Comment by bhadaway** [comment]
What exactly are you trying to achieve for the specific website in question, though?

Do you want the website to adjust to user's light/dark preference, do you want to force the website to only be light/dark, regardless of their preference? Have you tried adjusting any of the light/dark settings under _Appearance > Customize_?

**Comment by rickhellewell** [comment]
THanks for your response.
I've been researching this a bit, and I think that the CSS in the theme
needs to 'sense' whether the user's browser settings have been set to
'dark' mode, and adjust the CSS accordingly.

The one site where I have identified this is
https://www.mariamcshaneauthor.com . It is a subsite of bkwriters.com and
uses a child theme of Pages; just some minor changes to allow the use of
the child theme.

In particular on that site, going to dark mode makes the content of a page
black text on black background. I see this on my Android/Samsung phone,
which sets dark mode by default in Chrome. If I change Chrome to use light
mode, the page content is visible.

So there needs to be some CSS that can adjust the text content if dark mode
is enabled. Not sure what that is - still researching. The MSDN links might
be a starting point.

I'm not sure how best to do that, though. There's some conflicting
information in the search results; I'm still looking at it. But you can see
it in Developer's mode if you use the Inspect tool, then go into mobile
device emulation. Then you can use the dark and light icons to see the
effect.

Hope this helps...Let me know if you need more information.

...Rick...

**Comment by bhadaway** [comment]
Pages already handles all this via CSS and under _Appearance > Customize > Layout & Display_.

If you need to alter the styles further, you can add the following to _Appearance > Customize > Additional CSS_ and style as needed:

```
@media(prefers-color-scheme:dark){}
@media(prefers-color-scheme:light){}
```

Anecdotally, for what it's worth, almost no one explicitly selects Light Mode; instead, they simply don't turn on Dark Mode. Additionally, some sites are simply "light" or "dark," stylistically, without necessarily having anything to do with a user's light or dark mode preference.

Throw in accessibility and accessibility tools like the one it sounds like you're referring to, often an invert colors trick, and you have a whole can of worms spilling over.

Even when you fully understand this issue, you won't fully understand this issue, nor will you be able to make it a perfect experience for 100% of people. You can only do your best.

**Comment by rickhellewell** [comment]
The issues is that the CSS used by Pages doesn't display content properly when the user sets their browser mode to 'dark'. On a Page or Post, the page/post title is black on black, the content is black on black, and other colors are not always visible.  

All of this is a CSS issue with the Pages styles. They are not specified properly for the possibility that dark mode is enabled. 

And, dark mode is enabled by default on smaller devices (phones, tablets, etc) because the browser on the device (usually Chrome) defaults to dark mode to save battery. (A white background takes more energy to display than a black background.)

And there may be some issues with accessibility functions of the theme due to 'dark' issues.   There are tons of CSS that needs to be adjusted in the theme to provide true compatibility/readability when the device is in Dark mode. You can use a media query for dark mode to adjust colors, but it might be better to adjust colors by using the 'light-dark' function for color elements (See https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark ), although this is not fully supported by all browser.

You might be able to do this with the 'color-scheme' CSS directives - see https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme ). This is more widely supported. 

This might work; according to some quick testing (it forces the 'light' mode, although it overrides user preferences and is not a good choice, perhaps):

```
@media (prefers-color-scheme: dark) {
:root {
  color-scheme: only light;
}

* {
  color: light-dark(black, white);
  background-color: light-dark(white, black);
}

  }

```

In any event, the CSS in the theme needs to be modified to handle cases where the user might set their browser preference to dark mode.

**Comment by bhadaway** [comment]
I don't deny that you're experiencing these issues, but I just double-checked the demo (https://wp-themes.com/pages/) in both light and dark modes, and it displays correctly. Also note that this theme is explicitly designed and tested to handle light/dark modes and accessibility in the first place (this isn't an afterthought).

By no means am I claiming that the theme is perfect and doesn't likely need improvements (improvements are always going to be needed), I'm just not sure that the theme is responsible for this specific issue you've come across. If I'm wrong, I'd love to fix the issue, but I'm not able to recreate the issue you're experiencing at the moment.

Would you mind running through the steps to recreate again on https://wp-themes.com/pages/, and please share those steps with me to follow if the issue still presents?

**Comment by rickhellewell** [comment]
Thanks for your reply. Your demo page works properly, as you said.

But - I looked at the source code of your demo page. In there, is this CSS
statement (line 68 of View Page Source)

@media(prefers-color-scheme:dark){body{color:#ddd;background:#111}

Although that media directive appears on the demo site, I cannot find where
that is defined in your theme source files (version 1.15)  I can't find
that directive in the
https://themes.trac.wordpress.org/browser/pages/1.1.5/style.css file.

That is the directive that 'fixes' the issue on your demo site, but where
is it in your actual theme files?  It is not in styles.css, I don't see it
in any of the templates.

I am also not sure where the files associated with this line (in
functions.php) are located in the Trac
wp_enqueue_style( 'pages-style', get_stylesheet_uri() );



Where does the

@media(prefers-color-scheme:dark){body{color:#ddd;background:#111}
come from? I can add that via Custom CSS to fix the issue on my site,
but where is it in your demo site?

Thanks...Rick..





On Fri, Apr 5, 2024 at 8:44 PM Bryan Hadaway ***@***.***>
wrote:
>
> I don't deny that you're experiencing these issues, but I just
double-checked the demo (https://wp-themes.com/pages/) in both light and
dark modes, and it displays correctly. Also note that this theme is
explicitly designed and tested to handle light/dark modes and accessibility
in the first place (this isn't an afterthought).
>
> By no means am I claiming that the theme is perfect and doesn't likely
need improvements (improvements are always going to be needed), I'm just
not sure that the theme is responsible for this specific issue you've come
across. If I'm wrong, I'd love to fix the issue, but I'm not able to
recreate the issue you're experiencing at the moment.
>
> Would you mind running through the steps to recreate again on
https://wp-themes.com/pages/, and please share those steps with me to
follow if the issue still presents?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by bhadaway** [comment]
You need to go to _Appearance > Customize > Layout & Display > And make sure that "Dark Mode" and "No Dark Mode" are toggled off_.

Additionally, you may need to make sure that you remove any custom CSS, plugins, or other customizations you may have added related to Light/Dark Mode.

The theme works how you want it to out-of-the-box.

**Comment by rickhellewell** [comment]
Well, yes. But I was trying to understand how the CSS worked - and where
the media statement came from. I can't find it in the pages style.css. Or
anywhere else.

**Comment by bhadaway** [comment]
It's a conditional, controlled by the above settings (found in _customizer.php_); it's not hard-coded into the stylesheet.
