### ISSUE TITLE
Block Builder appears in results for "Post Formats"

### ISSUE THREAD

**Issue by mikeritter** [bhadaway/support#2]
I am using WordPress 5.9.

I am looking to use Post Formats in my sites.

When I search the themes with "Post Formats" filter.

Block Builder pops up in the results, however in the editor there is no field to select Post Format.

https://wordpress.org/themes/tags/post-formats/

**Comment by bhadaway** [comment]
Oops!

This is my first block theme, and to be honest, it's all a little experimental. It's still considered a beta feature within WordPress itself.

Here's an interesting read: https://wptavern.com/how-do-post-formats-fit-into-a-block-theme-world

The takeaway seems to be that "post formats" in a block theme are an obsolete concept.

By the way, are you sure you wanted to use this theme in general anyway? It's the most minimalist block theme in existence (intentionally), but I'm just wondering if that was what you wanted, regardless of the tag issue. In any case, thanks for the heads up. Removing the tag.

**Comment by mikeritter** [comment]
NOTE: I did add the post formats hook in my local version of your theme (just for trying out) then added a plugin to enable classic editor.

New editor does not show the option in post editor in settings / post tab. UGH!

I had read Justin's post but was hoping for a quick workaround.

And, YES, I intentionally wanted a minimalist theme I could enhance.

ASIDE >>>
RE: this being "experimental", I am finding this more and more with the block editor and wishing Automattic / the WP community had continued to support a stable major release while hashing out the block ecosystem in a different major release.

**Comment by bhadaway** [comment]
Ah, well, I firmly stand with Classic concerning the Classic vs Block debate.

In fact, this is the only "block" thing I've ever done. The rest of it is 99.9% classic.

Check out https://wordpress.org/themes/blankslate/ instead. It doesn't have any post formats either, but it's the most minimalist classic theme and you'll easily be able to add custom post formats to it.
