### ISSUE TITLE
The login address is in the source code!

### ISSUE THREAD

**Issue by imandehghanifiroozabadi** [bhadaway/support#8]
Hello
I changed the login address with security plugins, the login address is still in the source and I think this is a big bug of this format! please help me.

My website: https://howdiscover.com/

The page I need help with: https://howdiscover.com/blog/how-to-turn-off-a-business-account-on-instagram/

**Comment by bhadaway** [comment]
While Publishers is intentionally a super opinionated theme that makes bold choices, _/login_ is actually a default, built-in login page redirect for WordPress. If you're using a custom login page supplied by a plugin for example, they should be redirecting _/login_ properly.

Sounds like you'll need to do it manually though, so I'd add the following to your _.htaccess_ file:

`redirect /login /whatever-the-new-login-slug-is`
